name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ vars.TEST1 }}" && exit 1

      - run: |
          echo "Add other actions to build"
          echo "Test and deploy your project"
